更新Workflow

diff --git a/.github/workflows/fork-sync.yml b/.github/workflows/fork-sync.yml
--- a/.github/workflows/fork-sync.yml
+++ b/.github/workflows/fork-sync.yml
@@ -1,24 +1,51 @@
-name: Sync Fork
+name: 'Upstream Sync'
+
+permissions:
+  contents: write
 
 on:
   schedule:
-    - cron: '0 7 */2 * *' # every month
-  workflow_dispatch: # on button click
+    - cron: "0 6 * * *" # At 06:00, every day
+  workflow_dispatch:  # click the button on Github repo!
+    inputs:
+      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
+        description: 'Fork Sync Test Mode'
+        type: boolean
+        default: false
 
 jobs:
-  sync:
-
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
     steps:
-      - uses: tgymnich/fork-sync@v2.0.10
+      # REQUIRED step
+      # Step 1: run a standard checkout action, provided by github
+      - name: Checkout target repo
+        uses: actions/checkout@v3
         with:
-          auto_approve: true
-          merge_method: rebase
-          pr_title: 同步源仓库
-          ignore_fail: true
-          token: ${{ secrets.SYNC_TOKEN }}
-          owner: ChatGPTNextWeb
-          repo: NextChat
-          base: main
-          head: main
+          # optional: set the branch to checkout,
+          # sync action checks out your 'target_sync_branch' anyway
+          ref: main
+          # REQUIRED if your upstream repo is private (see wiki)
+          persist-credentials: false
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
+        with:
+          upstream_sync_repo: ChatGPTNextWeb/NextChat
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.SYNC_TOKEN }} # automatically generated, no need to set
+
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+          exit 1
